import pickle
import pycountry

tags = {
	"Africa Day" : "africaday",
	"Ambassador for Peace" : "afp",
	"Ambassadors for Peace" : "afp",
	"American Clergy Leadership Conference" : "aclc",
	"American Leadership Conference" : "alc",
	"Balkans" : "balkans",
	"Global Day of Parents" : "gdp",
	"International Association of Parlimentarians for Peace" : "iapp",
	"International Day of Families" : "idp",
	"International Day of Peace" : "idp",
	"International Leadership Conference" : "ilc",
	"International Women's Day" : "iwd",
	"International Womens Day" : "iwd",
	"International Women Day" : "iwd",
	"International Women Day" : "iwd",
	"International Year of the Family" : "internationalyearofthefamily",
	"Interreligious Association for Peace and Development" : "iapd",
	"Intereligious Association for Peace and Development" : "iapd",
	"Interreligious Leadership Conference" : "irlc",
	"Intereligious Leadership Conference" : "irlc",
	"Peace Road" : "peaceroad",
	"Religious Youth Service" : "rys",
	"Sunhak" : "sunhakpeaceprize",
	"Sustainable Development" : "sdg",
	"Washington Times" : "washingtontimes",
	"Women's Federation for World Peace" : "wfwp",
	"Womens Federation for World Peace" : "wfwp",
	"Women Federation for World Peace" : "wfwp",
	"World Summit" : "worldsummit",
	"Afghanistan" : "Afghanistan",
	"Albania" : "Albania",
	"Algeria" : "Algeria",
	"Andorra" : "Andorra",
	"Angola" : "Angola",
	"Antigua" : "Antigua",
	"Argentina" : "Argentina",
	"Armenia" : "Armenia",
	"Australia" : "Australia",
	"Austria" : "Austria",
	"Azerbaijan" : "Azerbaijan",
	"Bahamas" : "Bahamas",
	"Bahrain" : "Bahrain",
	"Bangladesh" : "Bangladesh",
	"Barbados" : "Barbados",
	"Belarus" : "Belarus",
	"Belgium" : "Belgium",
	"Belize" : "Belize",
	"Benin" : "Benin",
	"Bhutan" : "Bhutan",
	"Bolivia" : "Bolivia",
	"Bosnia" : "Bosnia",
	"Botswana" : "Botswana",
	"Brazil" : "Brazil",
	"Brunei" : "Brunei",
	"Bulgaria" : "Bulgaria",
	"Burkina" : "Burkina",
	"Burundi" : "Burundi",
	"Cambodia" : "Cambodia",
	"Cameroon" : "Cameroon",
	"Canada" : "Canada",
	"CapeVerde" : "CapeVerde",
	"CentralAfricanRep" : "CentralAfricanRep",
	"Chad" : "Chad",
	"Chile" : "Chile",
	"China" : "China",
	"Colombia" : "Colombia",
	"Comoros" : "Comoros",
	"Congo" : "Congo",
	"CostaRica" : "CostaRica",
	"Croatia" : "Croatia",
	"Cuba" : "Cuba",
	"Cyprus" : "Cyprus",
	"CzechRepublic" : "CzechRepublic",
	"Denmark" : "Denmark",
	"Djibouti" : "Djibouti",
	"Dominica" : "Dominica",
	"DominicanRepublic" : "DominicanRepublic",
	"EastTimor" : "EastTimor",
	"Ecuador" : "Ecuador",
	"Egypt" : "Egypt",
	"ElSalvador" : "ElSalvador",
	"Equatorial Guinea" : "Equatorial Guinea",
	"Eritrea" : "Eritrea",
	"Estonia" : "Estonia",
	"Ethiopia" : "Ethiopia",
	"Fiji" : "Fiji",
	"Finland" : "Finland",
	"France" : "France",
	"Gabon" : "Gabon",
	"Gambia" : "Gambia",
	"Georgia" : "Georgia",
	"Germany" : "Germany",
	"Ghana" : "Ghana",
	"Greece" : "Greece",
	"Grenada" : "Grenada",
	"Guatemala" : "Guatemala",
	"Guinea" : "Guinea",
	"GuineaBissau" : "GuineaBissau",
	"Guyana" : "Guyana",
	"Haiti" : "Haiti",
	"Honduras" : "Honduras",
	"Hungary" : "Hungary",
	"Iceland" : "Iceland",
	"India" : "India",
	"Indonesia" : "Indonesia",
	"Iran" : "Iran",
	"Iraq" : "Iraq",
	"Ireland" : "Ireland",
	"Israel" : "Israel",
	"Italy" : "Italy",
	"IvoryCoast" : "IvoryCoast",
	"Jamaica" : "Jamaica",
	"Japan" : "Japan",
	"Jordan" : "Jordan",
	"Kazakhstan" : "Kazakhstan",
	"Kenya" : "Kenya",
	"Kiribati" : "Kiribati",
	"Korea" : "Korea",
	"Kosovo" : "Kosovo",
	"Kuwait" : "Kuwait",
	"Kyrgyzstan" : "Kyrgyzstan",
	"Laos" : "Laos",
	"Latvia" : "Latvia",
	"Lebanon" : "Lebanon",
	"Lesotho" : "Lesotho",
	"Liberia" : "Liberia",
	"Libya" : "Libya",
	"Liechtenstein" : "Liechtenstein",
	"Lithuania" : "Lithuania",
	"Luxembourg" : "Luxembourg",
	"Macedonia" : "Macedonia",
	"Madagascar" : "Madagascar",
	"Malawi" : "Malawi",
	"Malaysia" : "Malaysia",
	"Maldives" : "Maldives",
	"Mali" : "Mali",
	"Malta" : "Malta",
	"MarshallIslands" : "MarshallIslands",
	"Mauritania" : "Mauritania",
	"Mauritius" : "Mauritius",
	"Mexico" : "Mexico",
	"Micronesia" : "Micronesia",
	"Moldova" : "Moldova",
	"Monaco" : "Monaco",
	"Mongolia" : "Mongolia",
	"Montenegro" : "Montenegro",
	"Morocco" : "Morocco",
	"Mozambique" : "Mozambique",
	"Myanmar" : "Myanmar",
	"Namibia" : "Namibia",
	"Nauru" : "Nauru",
	"Nepal" : "Nepal",
	"Netherlands" : "Netherlands",
	"NewZealand" : "NewZealand",
	"Nicaragua" : "Nicaragua",
	"Niger" : "Niger",
	"Nigeria" : "Nigeria",
	"Norway" : "Norway",
	"Oman" : "Oman",
	"Pakistan" : "Pakistan",
	"Palau" : "Palau",
	"Panama" : "Panama",
	"PapuaNewGuinea" : "PapuaNewGuinea",
	"Paraguay" : "Paraguay",
	"Peru" : "Peru",
	"Philippines" : "Philippines",
	"Poland" : "Poland",
	"Portugal" : "Portugal",
	"Qatar" : "Qatar",
	"Romania" : "Romania",
	"Russia" : "Russia",
	"Rwanda" : "Rwanda",
	"StKitts" : "StKitts",
	"StLucia" : "StLucia",
	"SaintVincent" : "SaintVincent",
	"Samoa" : "Samoa",
	"SanMarino" : "SanMarino",
	"SaoTome" : "SaoTome",
	"SaudiArabia" : "SaudiArabia",
	"Senegal" : "Senegal",
	"Serbia" : "Serbia",
	"Seychelles" : "Seychelles",
	"SierraLeone" : "SierraLeone",
	"Singapore" : "Singapore",
	"Slovakia" : "Slovakia",
	"Slovenia" : "Slovenia",
	"SolomonIslands" : "SolomonIslands",
	"Somalia" : "Somalia",
	"SouthAfrica" : "SouthAfrica",
	"SouthSudan" : "SouthSudan",
	"Spain" : "Spain",
	"SriLanka" : "SriLanka",
	"Sudan" : "Sudan",
	"Suriname" : "Suriname",
	"Swaziland" : "Swaziland",
	"Sweden" : "Sweden",
	"Switzerland" : "Switzerland",
	"Syria" : "Syria",
	"Taiwan" : "Taiwan",
	"Tajikistan" : "Tajikistan",
	"Tanzania" : "Tanzania",
	"Thailand" : "Thailand",
	"Togo" : "Togo",
	"Tonga" : "Tonga",
	"Trinidad" : "Trinidad",
	"Tunisia" : "Tunisia",
	"Turkey" : "Turkey",
	"Turkmenistan" : "Turkmenistan",
	"Tuvalu" : "Tuvalu",
	"Uganda" : "Uganda",
	"Ukraine" : "Ukraine",
	"UnitedArabEmirates" : "UnitedArabEmirates",
	"UnitedKingdom" : "UnitedKingdom",
	"UnitedStates" : "UnitedStates",
	"Uruguay" : "Uruguay",
	"Uzbekistan" : "Uzbekistan",
	"Vanuatu" : "Vanuatu",
	"VaticanCity" : "VaticanCity",
	"Venezuela" : "Venezuela",
	"Vietnam" : "Vietnam",
	"Yemen" : "Yemen",
	"Zambia" : "Zambia",
	"Zimbabwe" : "Zimbabwe"
}





'''
with open("tags.pickle", "wb") as _file:
	pickle.dump(tags, _file)
'''


with open("tags.pickle", "rb") as _file:
	tags = pickle.load(_file)
	for key in tags:
		print(key, " : ", tags[key])
